=== UO294130/sew2/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.uniovi.es"
xmlns= "http://www.uniovi.es"
 elementFormDefault="qualified" >
 
	<xs:element name="circuitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="circuito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="datosCircuito" />
				<xs:element ref="recursosExternos" />
				<xs:element ref="ubicacionesCircuito" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="datosCircuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="datosPista" />
				<xs:element ref="horarioCircuito" />
				<xs:element ref="datosCarrera" />
				<xs:element ref="localizacionCircuito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="datosPista">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudCarrera" />
				<xs:element ref="anchuraMedia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudCarrera">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchuraMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="horarioCircuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fechaCarrera" />
				<xs:element ref="horaCarrera" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fechaCarrera" type="xs:date" />
	<xs:element name="horaCarrera" type="xs:time" />
	<xs:element name="datosCarrera">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="numeroVueltas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="numeroVueltas" type="xs:integer" />
	<xs:element name="localizacionCircuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="recursosExternos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="referencias" />
				<xs:element ref="multimedia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="descripcion" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="multimedia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="imagenes" />
				<xs:element ref="videos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="imagenes">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="imagen" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="imagen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enlace" />
			</xs:sequence>
			<xs:attribute name="descripcion" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enlace" />
			</xs:sequence>
			<xs:attribute name="descripcion" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="enlace" type="xs:string" />
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="ubicacionesCircuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadasSalida" />
				<xs:element ref="tramosCircuito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenada">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="LongitudType">
		<xs:restriction base = "xs:float">
			<xs:minInclusive value= "-180.0"/>
			<xs:maxInclusive value= "180.0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="LongitudType">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="LatitudType">
		<xs:restriction base = "xs:float">
			<xs:minInclusive value= "-90"/>
			<xs:maxInclusive value= "90"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="LatitudType">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadasSalida">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenada" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramosCircuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenada" />
				<xs:element ref="numeroSector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="numeroSector" type="xs:integer" />
</xs:schema>

=== UO294130/sew2/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuitos 
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation ="http://www.uniovi.es circuito.xsd">

<circuito nombre="Red Bull Ring">
    <datosCircuito>
        <datosPista>
            <longitudCarrera unidad = "km">4.318</longitudCarrera>
            <anchuraMedia unidad = "m">12.5</anchuraMedia>
        </datosPista>
        
        <horarioCircuito>
            <fechaCarrera> 2024-06-30 </fechaCarrera>
            <horaCarrera >15:00:00 </horaCarrera>
        </horarioCircuito>
        
        <datosCarrera>
            <numeroVueltas>71</numeroVueltas>
        </datosCarrera>
        
        <localizacionCircuito>
            <localidad>Knittelfeld</localidad>
            <pais>Austria</pais>
        </localizacionCircuito>
    </datosCircuito>
    <recursosExternos>
        <referencias>
            <referencia descripcion = "referencia 1"> https://www.dazn.com/es-ES/news/motor/circuito-red-bull-ring-donde-esta-como-es-caracteristicas-como-llegar-fotos-escenario-gp-austria-mundial-f1-motogp/11mzmm2gb230a1fcbe6anph2tc </referencia>
            <referencia descripcion = "referencia 2"> https://es.wikipedia.org/wiki/Red_Bull_Ring </referencia>
            <referencia descripcion = "referencia 2"> https://www.statsf1.com/es/circuit-spielberg.aspx </referencia>
        </referencias>

        <multimedia>
            <imagenes>
                <imagen descripcion = "Imagen del circuito"> 
                <enlace> circuito.jpg </enlace> 
                </imagen>
                <imagen descripcion = "Imagen del circuito visto desde arriba"> 
                    <enlace> red-bull-ring-vista-desde-arriba.jpg </enlace> 
                </imagen>
                <imagen descripcion = "Imagen de la salida del circuito"> 
                    <enlace> Salida-redbullring.webp  </enlace> 
                </imagen>
            </imagenes>

            <videos>
                <video descripcion ="Salida de la carrera">
                    <enlace> inicio_carrera.mp4</enlace>
                </video>
                <video descripcion = "Final de la carrera">
                    <enlace> final_carrera.mp4 </enlace>
                </video>
            </videos>

        </multimedia>
    </recursosExternos>


<ubicacionesCircuito>
    <coordenadasSalida>
        <coordenada>
            <longitud unidad = "dd"> 14.764722 </longitud>
            <latitud unidad = "dd"> 47.220000 </latitud>
            <altitud unidad = "m"> 678 </altitud>
        </coordenada>
    </coordenadasSalida>

    <tramosCircuito>
         <tramo>
            
            <distancia unidad = "m"> 290 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.761029 </longitud>
                <latitud unidad = "dd"> 47.219275 </latitud>
                <altitud unidad = "m"> 691 </altitud>
            </coordenada>
            <numeroSector> 1 </numeroSector>
        </tramo>

        <tramo>
            <distancia unidad = "m"> 25.79 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.760855 </longitud>
                <latitud unidad = "dd"> 47.219331 </latitud>
                <altitud unidad = "m"> 694 </altitud>
            </coordenada>
            <numeroSector> 1 </numeroSector>
        </tramo>

        <tramo>
            <distancia unidad = "m"> 94.04 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.760162 </longitud>
                <latitud unidad = "dd">  47.220050 </latitud>
                <altitud unidad = "m"> 699 </altitud>
            </coordenada>
            <numeroSector> 1 </numeroSector>
        </tramo>
        
        
        <tramo>
            <distancia unidad = "m"> 252.2 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.758205 </longitud>
                <latitud unidad = "dd"> 47.222028 </latitud>
                <altitud unidad = "m"> 699 </altitud>
            </coordenada>
            <numeroSector> 1 </numeroSector>
        </tramo>

        <tramo>
            <distancia unidad = "m"> 277.89 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.7563657 </longitud>
                <latitud unidad = "dd">  47.224467 </latitud>
                <altitud unidad = "m"> 707 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo>
        
        <tramo>
            <distancia unidad = "m"> 285.27 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.753998 </longitud>
                <latitud unidad = "dd"> 47.226153 </latitud>
                <altitud unidad = "m"> 743 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo>

        <tramo>
            <distancia unidad = "m"> 14.86 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.754095 </longitud>
                <latitud unidad = "dd"> 47.226299 </latitud>
                <altitud unidad = "m"> 745 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo>

        <tramo>
            <distancia unidad = "m"> 184.35 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.756111 </longitud>
                <latitud unidad = "dd"> 47.226389 </latitud>
                <altitud unidad = "m"> 743 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo> 

        <tramo> 
            <distancia unidad = "m"> 420.34 </distancia>
            <coordenada>
                <longitud unidad = "DMS"> 14.761372 </longitud>
                <latitud unidad = "DMS"> 47.225872 </latitud>
                <altitud unidad = "m"> 725 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo>

        <tramo> 
            <distancia unidad = "m"> 198.64 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.764376 </longitud>
                <latitud unidad = "dd"> 47.225749 </latitud>
                <altitud unidad = "m"> 715 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo>

        <tramo>  
            <distancia unidad = "m"> 37.8 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.764562 </longitud>
                <latitud unidad = "dd"> 47.225300 </latitud>
                <altitud unidad = "m"> 713 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo>

        <tramo>
            <distancia unidad = "m"> 92.98 </distancia>
            <coordenada> 
                <longitud unidad = "dd"> 14.763889 </longitud>
                <latitud unidad = "dd"> 47.224722 </latitud>
                <altitud unidad = "m"> 709 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo>

        <tramo> 
            <distancia unidad = "m"> 82.43 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.762652 </longitud>
                <latitud unidad = "dd"> 47.224376 </latitud>
                <altitud unidad = "m"> 707 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo>

        <tramo> 
            <distancia unidad = "m"> 119.45 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.761439 </longitud>
                <latitud unidad = "dd"> 47.224423 </latitud>
                <altitud unidad = "m"> 708 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo>

        <tramo> 
            <distancia unidad = "m"> 147.01 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.759425 </longitud>
                <latitud unidad = "dd"> 47.224644 </latitud>
                <altitud unidad = "m"> 711 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo>

        <tramo> 
            <distancia unidad = "m"> 65.42 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.758611 </longitud>
                <latitud unidad = "dd"> 47.224167 </latitud>
                <altitud unidad = "m"> 705 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo>

        <tramo>
            <distancia unidad = "m"> 66.45 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.758629 </longitud>
                <latitud unidad = "dd"> 47.223653 </latitud>
                <altitud unidad = "m"> 705 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo>

        <tramo> 
            <distancia unidad = "m"> 204.65 </distancia>
            <coordenada>
                <longitud unidad = "dd">14.759859 </longitud>
                <latitud unidad = "dd"> 47.222224 </latitud>
                <altitud unidad = "m"> 691 </altitud>
            </coordenada>
            <numeroSector> 2 </numeroSector>
        </tramo>

        <tramo> 
            <distancia unidad = "m"> 63.23 </distancia>
            <coordenada>
                <longitud unidad = "dd"> 14.760796 </longitud>
                <latitud unidad = "dd"> 47.222101 </latitud>
                <altitud unidad = "m"> 690 </altitud>
            </coordenada>
            <numeroSector> 3 </numeroSector>
        </tramo>

        <tramo>  
            <distancia unidad = "m"> 55.22 </distancia>
            <coordenada>
